name: CD_Terraform_Deployment

on:
  push:
    branches:
      - main
  paths:
      - 'terraform/**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: production
    steps:
    # Configure AWS credential
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform fmt
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./terraform

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install -r key_requirements.txt

      - name: Generate and store secrets in AWS SSM
        run: python secret.py
        continue-on-error: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve ./tfplan
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        continue-on-error: false
